### ISSUE TITLE
CLI  install for runners should come from the same place

### ISSUE THREAD

**Issue by jduimovich** [redhat-actions/openshift-actions-runner#2]
The cli install for runner images containers fetches CLI from many sources. This should be consistent with the CLI installer as well as support install from target openshift clusters

**Comment by tetchel** [comment]
switched to install from mirror https://github.com/redhat-actions/openshift-actions-runner/commit/13009ca3fb5b07eb3e1fbcd281b2e74166de3aff

**Comment by tetchel** [comment]
opened another issue for the second part
